#!/usr/bin/python

from __future__ import division
from numpy import *
import matplotlib.pyplot as plt
import sys
import re
import getopt

if (sys.stdin.isatty()):        # Use command line arguments.
    try:
        fcns = sys.argv[1].split(';')
        minx = eval(sys.argv[2])
        maxx = eval(sys.argv[3])
        plt.xlim(minx, maxx)
    except:
        print "Too few arguments."
        exit()
    try:
        miny = float(sys.argv[4])
        maxy = float(sys.argv[5])
        plt.ylim(miny, maxy)
    except IndexError:
        pass
    x = linspace(minx, maxx, 100)
    for i, f in enumerate(fcns):
        y = eval(f)
        plt.plot(x, y, "-", linewidth=2)
else:                           # Use stdin.
    marker = '.'
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'l')
        for o, a in opts:
            if o == '-l':
                marker = '.-'
        x = []
        y = []
        for line in sys.stdin:
            line = line.strip()
            vals = re.split(r'\s+|\s*,\s*', line)
            x.append(vals[0])
            y.append(vals[1])
            plt.plot(x, y, marker)
    except:
        print "No stdin."

# Common.
plt.minorticks_on()
plt.grid(which='both', color='#aaaaaa')
plt.savefig(open('out.png', 'w'), format='png')
